### ISSUE TITLE
Is this the original data set from the CRH paper?

### ISSUE THREAD

**Issue by sdimple-chf** [kesavsivakumar/Resolving-Conflicts-in-Heterogeneous-Data--CRH_Framework#1]
Hi, thank you very much for sharing the code. Is the weather data set used here reported in the original CRH paper 'Resolving Conflicts in Heterogeneous Data by Truth Discovery and Source Reliability Estimation' ? Where did you get the raw weather data and the ground truth data? I look forward to your reply, thank you.

**Comment by kesavsivakumar** [comment]
@sdimple-chf Ig this is the original dataset used in the paper. Mailed the authors requesting the dataset and this is the data they shared with me.
